[package]
name = "loki"
version = "2.0.0"
edition = "2021"

[[bin]]
name = "loki"
path = "src/main.rs"

[[bin]]
name = "loki-util"
path = "src/loki_util/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.*"
walkdir = "2.5"
rustop = "1.1.*"
arrayvec = "0.7.*"
flexi_logger = "0.31"
colored = "2.0"
sysinfo = "0.33"
human_bytes = "0.4"
filesize = "0.2"
file-format = "0.26"
csv = "1.3"
md5 = "0.7"
sha1 = "0.10"
sha2 = "0.10.*"
hex = "0.4.*"
memmap2 = "0.9"
chrono = "0.4"
regex = "1"
yara-x = "1.10.0"
zip = "2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
